AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  jekyll-aws-comments

  App to accept a user comment and create a GitHub pull request containing the
  contents of the comment.

Parameters:
  CorsAllowOriginParameter:
    Type: String
    Default: "'*'"
    Description: Enter the host that will call the PostCommentsFunction. e.g. "'https://www.example.com'"

Globals:
  Function:
    Runtime: nodejs12.x
    Handler: index.handler
  Api:
    Cors:
      AllowOrigin:
        Ref: CorsAllowOriginParameter
      AllowHeaders: "'Content-Type'"
    EndpointConfiguration: REGIONAL

Resources:
  StaticCommentsTopic:
    Type: AWS::SNS::Topic

  PostCommentsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: post-comments/
      Role: !GetAtt StaticCommentsRole.Arn
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref StaticCommentsTopic
      Events:
        Comment:
          Type: Api
          Properties:
            Path: /comment
            Method: post

  CreatePullRequestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: create-pull-request/
      Role: !GetAtt StaticCommentsRole.Arn
      Timeout: 10
      Events:
        PullRequest:
          Type: SNS
          Properties:
            Topic: !Ref StaticCommentsTopic

  # Create a custom role that both functions can use.
  StaticCommentsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: StaticCommentsPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Resource: '*'
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - sns:*

Outputs:
  CommentApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/comment/"
